[build]
  publish = "."

[functions]
  directory = "netlify/functions"

# Seguridad + permitir embeber solo en Upcoach
[[headers]]
  for = "/*"
  [headers.values]
    # Permite scripts inline (onclick / <script> en index.html)
    # Permite fuentes de Google si las usas
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.openai.com; frame-ancestors https://upcoach.com https://*.upcoach.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

